# Generated by Django 5.1.3 on 2024-11-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_monitoringstation_alert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('alert_type', models.CharField(choices=[('illegal_logging', 'Illegal Logging'), ('wildlife_trafficking', 'Endangered Species Trafficking'), ('wildfire', 'Wildfire'), ('habitat_destruction', 'Habitat Destruction')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='SensorReading',
        ),
    ]
