# Generated by Django 5.1.3 on 2024-11-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alert_delete_sensorreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringstation',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
